src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Manager_Email__c</fullName>
        <description>Email address for Market Manager (Account Owner from PSG Salesforce)</description>
        <inlineHelpText>Email address for Market Manager</inlineHelpText>
        <label>Market Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Market_Manager_Name__c</fullName>
        <description>Name for Market Manager (Account Owner) from PSG Salesforce</description>
        <inlineHelpText>This is the Account Owner from PSG Salesforce</inlineHelpText>
        <label>Market Manager Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Connectivity_System__c.object
<CustomObject>
    <fields>
        <fullName>Connectivity_Vendor__c</fullName>
        <label>Connectivity Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Connectivity Systems</relationshipLabel>
        <relationshipName>Connectivity_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connectivity System</label>
    <nameField>
        <label>Connectivity System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connectivity Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Connectivity_System_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Connectivity_System__c</fullName>
        <label>Connectivity System</label>
        <referenceTo>Connectivity_System__c</referenceTo>
        <relationshipLabel>Connectivity System Contacts</relationshipLabel>
        <relationshipName>Connectivity_System_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connectivity System Contacts</relationshipLabel>
        <relationshipName>Connectivity_System_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Connectivity System Contact</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Connectivity System Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connectivity System Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting/Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Reservations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Commerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EQC Hotel Vendor Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expedia Quick Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise Service Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front Desk Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest Services Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health &amp; Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHG Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Content Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reservations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venere Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Venere Connect Hotel Vendor Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa Support</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Standard external contact</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

src/objects/PSG_User__c.object
<CustomObject>
    <description>List of Users who are active in PSG and not active in GSO who need to share information with GSO Users.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PSG User</label>
    <nameField>
        <label>PSG User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSG Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSG_User_Role__c.object
<CustomObject>
    <description>Junction between PSG Users and Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSG_User__c</fullName>
        <label>PSG User</label>
        <referenceTo>PSG_User__c</referenceTo>
        <relationshipLabel>PSG User Roles</relationshipLabel>
        <relationshipName>PSG_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Market Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revenue Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Line Managers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PSG User Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSG User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailWidgetWrapper.cls
public with sharing class EmailWidgetWrapper {
	
	public EmailWidgetWrapper (Connection__c myConnection, id myCaseId){
		this.myConnection = myConnection;
		this.templates = getTemplates();
		this.hotelContacts = getHotelContacts();
		this.vendorContacts = getVendorContacts();
		this.systemContacts = getSystemContacts();
		this.marketManagers = getMarketManagers();
		this.accountTeamMembers = getAccountTeamMembers();
		this.myCaseId = myCaseId;
	}
	
	public List<SelectOption> templates {get; set;}
	public List<SelectOption> hotelContacts {get; set;}
	public List<SelectOption> vendorContacts {get; set;}
	public List<SelectOption> systemContacts {get; set;}
	public List<SelectOption> marketManagers {get; set;}
	public List<SelectOption> accountTeamMembers {get; set;}
	public Connection__c myConnection {get; set;}
	public string hotelContact{get; set;}
	public id myCaseId{get; set;}
	
    public List<String> selectedVendorContacts{
		get{
			if (selectedVendorContacts == null) selectedVendorContacts = new List<String>();
			return selectedVendorContacts;
		} set;
	}
    public List<String> selectedSystemContacts{
		get{
			if (selectedSystemContacts == null) selectedSystemContacts = new List<String>();
			return selectedSystemContacts;
		} set;
	}
    public List<String> selectedMarketManagers{
		get{
			if (selectedMarketManagers == null) selectedMarketManagers = new List<String>();
			return selectedMarketManagers;
		} set;
	}
    public List<String> selectedAccountTeamMembers{
		get{
			if (selectedAccountTeamMembers == null) selectedAccountTeamMembers = new List<String>();
			return selectedAccountTeamMembers;
		} set;
	}
	
	public string template {
		get{
			if (template == null) return '';
			return template;							
		}set;
	}
	
    public PageReference sendConnectivityEmail(){
    	String fromEmailAddress = 'connect.eqc@3b49lbjwy8aaythyiuc5i84z4.m9grhmay.m.apex.sandbox.salesforce.com';
    	String retURL = EncodingUtil.urlEncode('/apex/ManageConnection?Id=' + this.myConnection.Id + '&' + ConnectionController.getCaseQueryString(this.myCaseId), 'UTF-8');
    	
    	PageReference emailURL = new PageReference ('/email/author/emailauthor.jsp?'
    												+ 'retURL=' + retURL // RETURN URL 
    												+ '&p2_lkid=' + this.hotelContact // ContactID
    												+ '&p3_lkid=' + myConnection.Id // RELATED TO WHATID
    												//+ '&p2=' + '' // TO: (CONTACT NAME)									
    												//+ '&p24=' + ccAddresses() // ADDITIONAL TO
    												+ '&p4=' + ccAddresses() // CC ADDRESS
    												+ '&p26=' + fromEmailAddress // FROM ADDRESS
    												+ '&template_id=' + this.template
    												); 
    	emailURL.setRedirect(true);
    	return emailURL;   	
	}
	
	// PRIVATE METHODS
	
	private string ccAddresses(){
		string ccAddresses = '';		
		ccAddresses += flattenStringList(this.selectedVendorContacts);		
		ccAddresses += flattenStringList(this.selectedSystemContacts);
		ccAddresses += flattenStringList(this.selectedAccountTeamMembers);
		return ccAddresses;
	}
	
    private string flattenStringList(List<String> myList){
    	String myStrings = '';
    	if (myList != null){
			for (String myString : myList){
				myStrings = myStrings + myString + '; ';
			}
		}
    	return myStrings;
	}
	
	private List<SelectOption> getTemplates() {
    	List<EmailTemplate> templates = [SELECT Id 
    										   ,Name 
    									   FROM EmailTemplate 
    									  WHERE FolderId IN (SELECT Id 
    									  					   FROM Folder 
    									  					  WHERE Name = 'Connectivity')
					  				   order by Name asc];
    									  					  
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','-- None -- '));
        for (EmailTemplate myTemplate : templates){        
        	options.add(new SelectOption(myTemplate.Id,myTemplate.Name));
        }
        return options;
	}

    private List<SelectOption> getHotelContacts() {
        List<SelectOption> options = new List<SelectOption>();      
        List<Account_Contact__c> hotelContacts = [SELECT Id
        												,Contact__c
        												,Contact__r.Email
        												,Contact__r.FirstName
        												,Contact__r.LastName 
        										    FROM Account_Contact__c 
        										   WHERE Account__c = :myConnection.Account__c];
        for (Account_Contact__c hotelContact : hotelContacts){
        	options.add(new SelectOption(hotelContact.Contact__c,hotelContact.Contact__r.FirstName + ' ' + hotelContact.Contact__r.LastName));
        }
        options.add(new SelectOption('','-- None -- '));
        return options;
    } 

    private List<SelectOption> getVendorContacts() {
        List<SelectOption> options = new List<SelectOption>();        
    	List<Account_Contact__c> vendorContacts = [SELECT Id
        												,Contact__r.Email
        												,Contact__r.FirstName
        												,Contact__r.LastName 
        										    FROM Account_Contact__c 
        										   WHERE Account__c = :myConnection.Connectivity_System__r.Connectivity_Vendor__c];
        for (Account_Contact__c vendorContact : vendorContacts){
        	options.add(new SelectOption(vendorContact.Contact__r.Email,vendorContact.Contact__r.FirstName + ' ' + vendorContact.Contact__r.LastName));
        }
        return options;
    } 
 
    private List<SelectOption> getSystemContacts() {
        List<SelectOption> options = new List<SelectOption>();
        
        List<Connectivity_System_Contact__c> systemContacts = [SELECT Id
        															  ,Contact__r.Email
        															  ,Contact__r.FirstName
        															  ,Contact__r.LastName 
        										    			  FROM Connectivity_System_Contact__c 
        										   				 WHERE Connectivity_System__c = :myConnection.Connectivity_System__c];       
        for (Connectivity_System_Contact__c systemContact : systemContacts){
        	options.add(new SelectOption(systemContact.Contact__r.Email,systemContact.Contact__r.FirstName + ' ' + systemContact.Contact__r.LastName));
        }
        return options;
    }

    private List<SelectOption> getMarketManagers() {
        List<SelectOption> options = new List<SelectOption>(); 
        if (myConnection.Account__r.Market_Manager_Email__c != null && myConnection.Account__r.Market_Manager_Name__c != null){       
        	options.add(new SelectOption(myConnection.Account__r.Market_Manager_Email__c, myConnection.Account__r.Market_Manager_Name__c));
        }
        return options;
    }
    private List<SelectOption> getAccountTeamMembers() {
        List<SelectOption> options = new List<SelectOption>(); 	        
        List<PSG_User_Role__c> accountTeamMembers = PSGUserRoleClass.findByAccount(myConnection.Account__c);
        										   
        for (PSG_User_Role__c accountTeamMember : accountTeamMembers){
        	options.add(new SelectOption(accountTeamMember.PSG_User__r.Email__c,accountTeamMember.PSG_User__r.Name + ' (' + accountTeamMember.Role__c + ')'));
        }	        
        return options;
    }     	
}