src/objects/Connection__c.object
<CustomObject>
    <label>Connection</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Connection Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rollout_Step__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Connectivity_Rollouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Connection__c</fullName>
        <label>Connection</label>
        <referenceTo>Connection__c</referenceTo>
        <relationshipName>Connectivity_Rollouts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollout_Step__c</fullName>
        <label>Rollout Step</label>
        <picklist>
            <picklistValues>
                <fullName>Enrollment Form Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Enrollment Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Form Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Mapping Chaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mapping Information Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rollout Step</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Rollout Step Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rollout Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RolloutStepClass.cls
public with sharing class RolloutStepClass {
	
	public static List<Rollout_Step__c> getRolloutStepsByConnectionId(Id connectionId){
		return [SELECT Id
                      ,Rollout_Step__c
                      ,OwnerId
                      ,Completed_Date__c
                      ,Case__c
                      ,Owner.Name
                 FROM  Rollout_Step__c
                WHERE  Connection__c = :connectionId
             order by Completed_Date__c asc nulls last];
	}
	
	public static Rollout_Step__c getRolloutStepById(Id rolloutStepId){
		return [SELECT Id
				  FROM Rollout_Step__c
				 WHERE Id = :rolloutStepId];
	}
	
    //Upsering a list touches even unchanged records. This simply pulls out the new steps and inserts them.
    public static void insertNewRolloutSteps(List<Rollout_Step__c> myRolloutSteps){
    	List<Rollout_Step__c> rolloutStepsToInsert = new List<Rollout_Step__c>();
    	for (Rollout_Step__c myRolloutStep : myRolloutSteps){
    		if (myRolloutStep.Id == null){
    			rolloutStepsToInsert.add(myRolloutStep);
    		}
    	}
    	if (rolloutStepsToInsert.size() > 0) insert rolloutStepsToInsert;    	
    }

}