unpackaged/objects/Agent_Work_Time__c.object
<CustomObject>
    <fields>
        <fullName>Last_Ping__c</fullName>
        <label>Last Ping</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_in_Seconds__c</fullName>
        <label>Time in Seconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Time__c</fullName>
        <label>Work Time</label>
        <referenceTo>Work_Time__c</referenceTo>
        <relationshipLabel>Agent Work Times</relationshipLabel>
        <relationshipName>Agent_Work_Times</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agent Work Time</label>
    <nameField>
        <displayFormat>AWN-{000000000}</displayFormat>
        <label>Agent Work Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Work Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Work_Time__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Time</relationshipLabel>
        <relationshipName>Work_Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Session__c</fullName>
        <label>Last Session</label>
        <summarizedField>Agent_Work_Time__c.Stop_Time__c</summarizedField>
        <summaryForeignKey>Agent_Work_Time__c.Work_Time__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Time_in_Seconds__c</fullName>
        <label>Time in Seconds</label>
        <summarizedField>Agent_Work_Time__c.Time_in_Seconds__c</summarizedField>
        <summaryForeignKey>Agent_Work_Time__c.Work_Time__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Agent_Work_Time__c</fullName>
        <formula>text(MOD( floor( Time_in_Seconds__c/60/60 ) ,24)) &amp; &quot;h &quot; &amp; text(MOD( floor( Time_in_Seconds__c/60 ) ,60)) &amp; &quot;m &quot; &amp; text(MOD( floor( Time_in_Seconds__c ) ,60)) &amp; &quot;s&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Agent Work Time</label>
        <type>Text</type>
    </fields>
    <label>Work Time</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Work Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Agent_Time_Report_Controller.cls
public with sharing class Agent_Time_Report_Controller {
	public List<Work_Time__c> getTopTenWorkTimes(){
		DateTime last7days = system.now().addDays(-7);
		List<Work_Time__c> topTenWorkTimes = [SELECT Id
													,Case__c
													,Case__r.Subject
													,Case__r.CaseNumber
													,Case__r.Priority
													,Total_Agent_Work_Time__c 
											   FROM  Work_Time__c 
											   WHERE Last_Session__c > :last7days
											   order by Time_in_Seconds__c desc limit 10];
		return topTenWorkTimes;
	}
	
	public integer getTotalSupportTime(){
		DateTime last24Hours = system.now().addHours(-24);
		system.debug (last24Hours);
		double runningTotal = 0;
		List<Agent_Work_Time__c> myAgentWorkTimes = [SELECT Id, Time_in_Seconds__c FROM Agent_Work_Time__c WHERE Last_Ping__c > : last24Hours];
		
		for (Agent_Work_Time__c myAgentWorkTime : myAgentWorkTimes){
			if (myAgentWorkTime.Time_in_Seconds__c != null){
				runningTotal = runningTotal + myAgentWorkTime.Time_in_Seconds__c;
			}
		}
		return integer.valueOf(runningTotal)/60;
	}
	
	public static List<AggregateResult> getUserTimes(){
		List<AggregateResult> userTimes = [SELECT CreatedById, CreatedBy.Name ownerName, sum(Time_in_Seconds__c)sum FROM Agent_Work_Time__c GROUP BY CreatedById, CreatedBy.Name ORDER BY sum(Time_in_Seconds__c) desc];
		return userTimes;
	}
}